language: python

python:
  - "3.8"

services:
  - docker

install:
  - for i in src/*/requirements.txt ; do pip install -r $i ; done
  - pip install -r src/test-requirements.txt

script:
  - ./src/build-support/check-requirements.sh
  - ./src/build-support/test-src-dir.sh py-common
  - ./src/build-support/test-src-dir.sh py-dm-aws-ecs-tags
  - ./src/build-support/test-src-dir.sh py-dm-aws-service-discovery
  - ./src/build-support/test-src-dir.sh py-ds-aws-s3
  - ./src/build-support/test-src-dir.sh py-ds-local
  - ./src/build-support/test-src-dir.sh py-entry-standalone
  - ( cd src && docker build -t local/nightjar-envoy-standalone -f Dockerfile.envoy-standalone . )
  - ( cd src && docker build -t local/nightjar-envoy-central -f Dockerfile.envoy-central . )
