FROM envoyproxy/envoy-alpine:v1.13.0

RUN echo "start" \
  && apk upgrade --update \
  && apk add --update bash python3 \
  && python3 -m pip install --upgrade pip \
  && python3 pip install pystache \
  && echo "end"

COPY / /nightjar-root

RUN echo "start" \
    && chmod +x /nightjar-root/shell-tests/*.sh \
    && echo "end"

CMD ["/bin/bash", "/nightjar-root/shell-tests/run-tests.sh"]
