
"""
Auto-generated validation code.
"""

from .proxy_input import validate_proxy_input_schema_yaml as validate_proxy_input
from .fetched_template_data_store import validate_fetched_template_data_store_schema_yaml as validate_fetched_template_data_store
from .fetched_configuration_data_store import validate_fetched_configuration_data_store_schema_yaml as validate_fetched_configuration_data_store
from .discovery_map import validate_discovery_map_schema_yaml as validate_discovery_map
from .commit_configuration_data_store import validate_commit_configuration_data_store_schema_yaml as validate_commit_configuration_data_store
from .commit_template_data_store import validate_commit_template_data_store_schema_yaml as validate_commit_template_data_store
