version: '3'


services:
  forwarder-food:
    build:
      context: service-key-forward/.
    # Communication to the services must be done through the gateway.
    # ports:
    #   - "3001:3000"
    environment:
      KEYS: health,serves
      HEALTH_VALUE: ok
      SERVES_VALUE: food
      FORWARD_KEYS: food
      FOOD_URL: http://gateway:3000/key/food
    depends_on:
      - gateway
    networks:
      default:
        aliases:
          - forwarder-food

  service-food-hamburger:
    build:
      context: service-key-forward/.
    environment:
      KEYS: food,health
      FOOD_VALUE: hamburger
      HEALTH_VALUE: ok
    networks:
      default:
        aliases:
          - service-food-hamburger

  service-food-hotdog:
    build:
      context: service-key-forward/.
    environment:
      KEYS: food,health
      FOOD_VALUE: hotdog
      HEALTH_VALUE: ok
    networks:
      default:
        aliases:
          - service-food-hotdog

  gateway:
    build:
      context: nightjar-standalone-local/.
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      NJ_PROXY_MODE: gateway
      NJ_NAMESPACE: default
      DATA_STORE_EXEC: python3 -m nightjar_ds_local
      NJ_DSLOCAL_TEMPLATE_FILE: /nightjar/local/03-templates.json
      NJ_DSLOCAL_CONFIGURATION_FILE: /nightjar/local/03-configurations.json
      DISCOVERY_MAP_EXEC: python3 -m nightjar_dm_local
      NJ_DMLOCAL_DATA_FILE: /nightjar/local/03-discovery-map.json
      # The configuration directory must be a writable directory by the nobody user.
      ENVOY_CONFIGURATION_DIR: /tmp/envoy
      NJ_LISTEN_PORT: 3000
      NJ_ADMIN_PORT: 3001
      DEBUG: "true"
    networks:
      default:
        aliases:
          - envoy
