version: '3'


services:
  forwarder-f1:
    build:
      context: service-key-forward/.
    # Communication to the services must be done through the gateway.
    # ports:
    #   - "3001:3000"
    environment:
      KEYS: f1
      FORWARD_KEYS: f1
      F1_URL: http://gateway:3000/key/s1
    depends_on:
      - service-s1
    networks:
      default:
        aliases:
          - forwarder-f1

  service-s1:
    build:
      context: service-key-forward/.
    # Communication to the services must be done through the gateway.
    # ports:
    #   - "3002:3000"
    environment:
      KEYS: s1
    networks:
      default:
        aliases:
          - service-s1

  gateway:
    build:
      context: nightjar-standalone-local/.
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      NJ_PROXY_MODE: gateway
      NJ_NAMESPACE: default

      # Discovery map uses a static file lookup, so it reuses the data-store
      # but with hard-coded discovery map information.
      DISCOVERY_MAP_EXEC: python3 -m nightjar_ds_local --document=discovery-map --action=fetch
      DATA_STORE_EXEC: python3 -m nightjar_ds_local
      NJ_DSLOCAL_FILE_TEMPLATES: /nightjar/local/01-templates.json
      NJ_DSLOCAL_FILE_DISCOVERY_MAP: /nightjar/local/01-discovery-map.json

      NJ_LISTEN_PORT: 3000
      NJ_ADMIN_PORT: 3001
      DEBUG: "true"

      # The configuration directory must be a writable directory by the nobody user.
      ENVOY_CONFIGURATION_DIR: /tmp/envoy
    networks:
      default:
        aliases:
          - envoy
